-- AlterTable
ALTER TABLE `user` MODIFY `userType` ENUM('TEACHER', 'STUDENT', 'SUPER_ADMIN') NOT NULL DEFAULT 'STUDENT',
    MODIFY `role` ENUM('TEACHER', 'STUDENT', 'SUPER_ADMIN') NOT NULL DEFAULT 'STUDENT';
